[project]
name = "agentpm-examples-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.2.16",
    "langchain-openai>=0.2.5",
    "openai>=1.51.0",
    "python-dotenv[cli]>=1.1.1",
    "agentpm>=0.1.0"
]

[tool.uv]
